apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: $AWS_CLUSTER_NAME
  region: $AWS_REGION

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 4
    volumeSize: 100
    ssh:
      allow: true # this will use ~/.ssh/id_rsa.pub as the default ssh key
